on: 
  push:
    branches:
      - main
      - dispatch

jobs:
  stac_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install stac-check

    - name: Run STAC check
      run: |
        urls="
          https://data.geo.admin.ch/api/stac/v0.9/
          https://data.geo.admin.ch/api/stac/v1/
        "
        for url in $urls; do
          stac-check --collections --item-collection --recursive --links --assets $url >> check.out
        done
        cat check.out

    - uses: actions/upload-artifact@v4
      with:
        name: check
        path: check.*
